name: stylish_bottom_bar
description: A stylish bottom navigation bar for flutter
version: 0.0.1+1
homepage: https://github.com/MarsadMaqsood/Stylish_bottom_bar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter